### PR TITLE
fix(MapValidator): Remove unnecessary linting

### PR DESCRIPTION
**Pull request by martinalbert**
## Description

Removes linting of variables in http call except input and do not validate types of arguments in inline call against result.

## Motivation and Context

Wrong linting errors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lukas-valenta** [comment]
pls don't merge until i look at it and create dev branch (thursday)

**Comment by Jakub-Vacek** [comment]
@lukas-valenta we plan to take a look at linting and its bugs at the end of the week  👍

**Comment by lukas-valenta** [comment]
i'm not sure this is the right approach. you process the url parameters as typescript, which is not how it's processed in onesdk. i think the approaches should be similar. so what i think this should do:
- check the parameters with regex
- for each of them: split them into path
- check if we have access to variable with that path
- check if the path is correct, e.g. if we have `input.something.x` and `something` is scalar, it should pass, if `something` is number, it should not

**Comment by martinalbert** [comment]
Yeah I know it's bad, but I think it should be part of constant folding solution in the future. I store variables only if they were set before. Input, operation or http call variables are not stored in stack, they're checked within jessie expression visit function. This same validation of input is done in constructs so I'll remove it and let you know.

**Comment by martinalbert** [comment]
@lukas-valenta it's still the same approach and it doesn't process expressions in Url as `sdk` does, but it would take lot of  time to refactor it. It should be refactored in the end though, considering validator chain ADR.

**Comment by lukas-valenta** [comment]
we're not doing validator chain, not now and maybe not ever. this looks okay in the tests, so i guess it's good enough for now

**Comment by martinalbert** [comment]
@lukas-valenta I updated custom jest matcher to be able to receive array of errors, you can have final look at it before merge? I did same thing in #82, #81, #80, #78.

**Pull request merged**
