### PR TITLE
fix: refactor script compilation

### PR DESCRIPTION
**Pull request by TheEdward162**
## Description
Refactor script compilation into an encapsulated module and reuse parts as relevant

## Motivation and Context
Script compilation and handling was happening in multiple places. Now it is happening in only one place and is reused across components.

Also sumbled upon wrong error locations in map validator so I fixed those as a happy mistake.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TheEdward162** [comment]
Jeez I wonder which dependecy update pulled in a `Python-2.0` licensed libwhateverthing. Investigating...

**Comment by lukas-valenta** [comment]
i'm not sure :thinking: that's probably not a question for me to answer

**Review by lukas-valenta — COMMENTED** [review]
looks good enough, ~~but add some tests for the new class~~

**Review by lukas-valenta — APPROVED** [review]

**Review by martinalbert — APPROVED** [review]

**Comment by martinalbert** [comment]
I also got to license-check problem in #89 😢

**Pull request merged**
